name: Test Ansible in Docker

on:
  push:
    branches:
      - main

jobs:
  test-ansible:
    runs-on: ubuntu-latest
    container: ubuntu:latest  # Run inside a fresh Ubuntu container

    steps:
      - name: Install dependencies
        run: |
          apt update
          apt install -y ansible

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Ansible syntax check
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/playbook.yml --syntax-check

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/playbook.yml
