name: Test Ansible in Docker

on:
  push:
    branches:
      - main

jobs:
  test-ansible:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
      options: --privileged  # Allow services inside container

    steps:
      - name: Install dependencies
        run: |
          apt update
          apt install -y ansible nginx
          mkdir -p /var/www/html

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Ansible syntax check
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/playbook.yml --syntax-check

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/playbook.yml

      - name: Verify Nginx is running
        run: |
          curl -I http://localhost || echo "Nginx failed to start"
